services:
  nginx:
    container_name: nginx
    image: nginx:alpine3.20
    ports:
      - "81:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "../../:/app"
    
  phpfpm:
    container_name: phpfpm
    # build:
    #   context: ../
    image: davialano11/nextgen:php-fpm-alpine
    volumes:
      - "./php.ini:/usr/local/etc/php/php.ini"
      - "../../:/app"

  postgres:
    container_name: postgres
    image: postgres:alpine3.20
    shm_size: 128mb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
